spring:
  application:
    name: notification-service
  mail:
    host: smtp.mail.ru
    port: 465
    username: latyshevshop@mail.ru
    password: AsjK4hQKbtTUkqygPEnm
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory: javax.net.ssl.SSLSocketFactory
          fallback: false


  #Kafka properties
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.bookshop.notificationservice.event.OrderPlacedEvent
      group-id: notificationId

server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${random.value}
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka