spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/MicroservicesTestDB
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          keycloak:
            #            client-id: spring-cloud-client
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/realms/dive-dev
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/dive-dev
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

openapi:
  service:
    title: user-service doc
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /user-service/swagger-ui.html
    oauth:
      client-id: springboot-be
      client-secret: b3URSNl3vxNR19kUZs7eZbwIKo6XQEcj
    enabled: true

server:
  port: 8180



realm: dive-dev
server-url: http://localhost:8181
client-id: admin-cli
grant-type: password
username: admin
password: admin