spring:
  application:
    name: inventory-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${random.value}
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka


openapi:
  service:
    title: inventory-service doc
    version: 1.0.0
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /inventory-service/swagger-ui.html